CREATE TABLE UPLOADFILE
(
    OID CHAR(32) PRIMARY KEY NOT NULL,
    NAME NVARCHAR(200),
    CREATOR NVARCHAR(50),
    CREATEDATE DATETIME,
    CONTENTTYPE VARCHAR(100),
    FILESIZE DECIMAL(18),
    PARENT VARCHAR(200),
    RESERV1 NVARCHAR(200),
    RESERV2 NVARCHAR(200),
    RESERV3 NVARCHAR(200)
);